import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
            <link
                href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;1,700&display=swap"
                rel="stylesheet"
            ></link>
        </Head>
    </>
);

export default Home;
